import { pgTable, uuid, text, boolean, timestamp } from 'drizzle-orm/pg-core';
import { estadoAliadoEnum, tipoNegocioEnum, origenClienteEnum } from './enums';

export const aliados = pgTable('aliados', {
  id: uuid('id').defaultRandom().primaryKey(),
  codigoAliado: text('codigo_aliado').unique().notNull(),
  nombreEstablecimiento: text('nombre_establecimiento').notNull(),
  tipoNegocio: tipoNegocioEnum('tipo_negocio').notNull(),
  nitRepLegal: text('nit_rep_legal').notNull(),
  departamento: text('departamento').notNull(),
  ciudad: text('ciudad').notNull(),
  direccion: text('direccion').notNull(),
  telefonoEstablecimiento: text('telefono_establecimiento'),
  vehiculosMesPromedio: text('vehiculos_mes_promedio'),
  tipoVehiculosPrincipales: text('tipo_vehiculos_principales'),
  tiempoOperacion: text('tiempo_operacion'),
  tieneCamaraComercio: boolean('tiene_camara_comercio'),
  nombreContacto: text('nombre_contacto').notNull(),
  cargoContacto: text('cargo_contacto'),
  celularContacto: text('celular_contacto').notNull(),
  correoContacto: text('correo_contacto').notNull(),
  estado: estadoAliadoEnum('estado').default('pendiente').notNull(),
  autorizaTratamientoDatos: boolean('autoriza_tratamiento_datos').default(false),
  autorizaVerificacionSARLAFT: boolean('autoriza_verificacion_sarlaft').default(false),
  aceptaObligacionesAliado: boolean('acepta_obligaciones_aliado').default(false),
  aceptaTerminos: boolean('acepta_terminos').default(false),
  porcentajeComision: text('porcentaje_comision'),
  totalComisionesHistorico: text('total_comisiones_historico'),
  ejecutivoAsignado: text('ejecutivo_asignado'),
  origenRegistro: origenClienteEnum('origen_registro'),
  nombreReferido: text('nombre_referido'),
  firmaDigital: text('firma_digital'),
  ipRegistro: text('ip_registro'),
  creadoEn: timestamp('creado_en').defaultNow().notNull(),
  actualizadoEn: timestamp('actualizado_en').defaultNow().notNull(),
  aprobadoEn: timestamp('aprobado_en'),
  ultimaActividad: timestamp('ultima_actividad'),
});
