import { pgTable, uuid, text, numeric, integer, boolean, jsonb } from 'drizzle-orm/pg-core';

export const bancosCatalogo = pgTable('bancos_catalogo', {
  id: uuid('id').defaultRandom().primaryKey(),
  nombre: text('nombre').notNull().unique(),
  codigo: text('codigo').unique(),
  activo: boolean('activo').default(true),
  tasaHibridoNuevo: numeric('tasa_hibrido_nuevo', { precision: 5, scale: 4 }),
  tasaHibridoUsado: numeric('tasa_hibrido_usado', { precision: 5, scale: 4 }),
  tasaGasolinaNuevo: numeric('tasa_gasolina_nuevo', { precision: 5, scale: 4 }),
  tasaGasolinaUsado: numeric('tasa_gasolina_usado', { precision: 5, scale: 4 }),
  tasaPublicoNuevo: numeric('tasa_publico_nuevo', { precision: 5, scale: 4 }),
  tasaPublicoUsado: numeric('tasa_publico_usado', { precision: 5, scale: 4 }),
  tasaPrenda: numeric('tasa_prenda', { precision: 5, scale: 4 }),
  tasaCompraCartera: numeric('tasa_compra_cartera', { precision: 5, scale: 4 }),
  edadMinima: integer('edad_minima'),
  edadMaxima: integer('edad_maxima'),
  modeloMinimo: integer('modelo_minimo'),
  plazoMaximoNuevos: integer('plazo_maximo_nuevos'),
  plazoMaximoUsados: integer('plazo_maximo_usados'),
  financiacionMaxima: integer('financiacion_maxima'),
  scoreMinimo: integer('score_minimo'),
  aprobacionEnLinea: boolean('aprobacion_en_linea'),
  montoMaximoLinea: numeric('monto_maximo_linea', { precision: 15, scale: 2 }),
  tiempoAprobacion: text('tiempo_aprobacion'),
  ingresoMinimoEmpleado: numeric('ingreso_minimo_empleado', { precision: 15, scale: 2 }),
  ingresoMinimoIndependiente: numeric('ingreso_minimo_independiente', { precision: 15, scale: 2 }),
  ingresoMinimoPensionado: numeric('ingreso_minimo_pensionado', { precision: 15, scale: 2 }),
  zonasRestriccion: jsonb('zonas_restriccion').$type<string[]>(),
  perfilesNoAtendidos: jsonb('perfiles_no_atendidos').$type<string[]>(),
  centralRiesgo: text('central_riesgo'),
  atiendeEmpresas: boolean('atiende_empresas'),
  atiendePublicos: boolean('atiende_publicos'),
  atiendeMotos: boolean('atiende_motos'),
});
