import { pgTable, uuid, text, integer, numeric, boolean, timestamp, jsonb } from 'drizzle-orm/pg-core';
import { tipoSolicitudEnum, estadoVehiculoEnum, tipoServicioEnum, claseVehiculoEnum, tipoDocumentoEnum, generoEnum, estadoCivilEnum, nivelEstudiosEnum, actividadEconomicaEnum, tipoContratoEnum, tipoViviendaEnum, estratoEnum, estadoSolicitudEnum, origenClienteEnum } from './enums';
import { aliados } from './aliados';

export const solicitudes = pgTable('solicitudes', {
  id: uuid('id').defaultRandom().primaryKey(),
  numeroReferencia: text('numero_referencia').unique().notNull(),
  tipoSolicitud: tipoSolicitudEnum('tipo_solicitud').notNull(),
  estado: estadoSolicitudEnum('estado').default('borrador').notNull(),
  pasoActual: integer('paso_actual').default(1),
  aliadoId: uuid('aliado_id').references(() => aliados.id),
  codigoAliado: text('codigo_aliado'),
  estadoVehiculo: estadoVehiculoEnum('estado_vehiculo'),
  tipoServicio: tipoServicioEnum('tipo_servicio'),
  claseVehiculo: claseVehiculoEnum('clase_vehiculo'),
  marca: text('marca'),
  linea: text('linea'),
  modelo: integer('modelo'),
  valorVehiculo: numeric('valor_vehiculo', { precision: 15, scale: 2 }),
  cuotaInicial: numeric('cuota_inicial', { precision: 15, scale: 2 }),
  porcentajeCuotaInicial: numeric('porcentaje_cuota_inicial', { precision: 5, scale: 2 }),
  valorFinanciar: numeric('valor_financiar', { precision: 15, scale: 2 }),
  plazoMeses: integer('plazo_meses'),
  entidadActual: text('entidad_actual'),
  saldoActual: numeric('saldo_actual', { precision: 15, scale: 2 }),
  primerNombre: text('primer_nombre'),
  segundoNombre: text('segundo_nombre'),
  primerApellido: text('primer_apellido'),
  segundoApellido: text('segundo_apellido'),
  tipoDocumento: tipoDocumentoEnum('tipo_documento'),
  numeroDocumento: text('numero_documento'),
  fechaExpedicion: text('fecha_expedicion'),
  lugarExpedicion: text('lugar_expedicion'),
  fechaNacimiento: text('fecha_nacimiento'),
  paisNacimiento: text('pais_nacimiento').default('Colombia'),
  departamentoNacimiento: text('departamento_nacimiento'),
  ciudadNacimiento: text('ciudad_nacimiento'),
  genero: generoEnum('genero'),
  estadoCivil: estadoCivilEnum('estado_civil'),
  numeroHijos: integer('numero_hijos'),
  personasCargo: integer('personas_cargo'),
  nivelEstudios: nivelEstudiosEnum('nivel_estudios'),
  profesion: text('profesion'),
  direccionResidencia: text('direccion_residencia'),
  departamento: text('departamento'),
  ciudad: text('ciudad'),
  barrio: text('barrio'),
  estrato: estratoEnum('estrato'),
  tiempoResidencia: text('tiempo_residencia'),
  celular: text('celular'),
  telefonoResidencia: text('telefono_residencia'),
  correoElectronico: text('correo_electronico'),
  tipoVivienda: tipoViviendaEnum('tipo_vivienda'),
  actividadEconomica: actividadEconomicaEnum('actividad_economica'),
  inicioActividad: text('inicio_actividad'),
  cargo: text('cargo'),
  tipoContrato: tipoContratoEnum('tipo_contrato'),
  nombreEmpresa: text('nombre_empresa'),
  nitEmpresa: text('nit_empresa'),
  actividadEmpresa: text('actividad_empresa'),
  codigoCIIU: text('codigo_ciiu'),
  direccionOficina: text('direccion_oficina'),
  ciudadOficina: text('ciudad_oficina'),
  telefonoOficina: text('telefono_oficina'),
  salarioFijo: numeric('salario_fijo', { precision: 15, scale: 2 }),
  salarioVariable: numeric('salario_variable', { precision: 15, scale: 2 }),
  pension: numeric('pension', { precision: 15, scale: 2 }),
  honorarios: numeric('honorarios', { precision: 15, scale: 2 }),
  arrendamientos: numeric('arrendamientos_ingreso', { precision: 15, scale: 2 }),
  utilidadActividad: numeric('utilidad_actividad', { precision: 15, scale: 2 }),
  otrosIngresos: numeric('otros_ingresos', { precision: 15, scale: 2 }),
  detalleOtrosIngresos: text('detalle_otros_ingresos'),
  totalIngresos: numeric('total_ingresos', { precision: 15, scale: 2 }),
  pagoArriendo: numeric('pago_arriendo', { precision: 15, scale: 2 }),
  gastosFamiliares: numeric('gastos_familiares', { precision: 15, scale: 2 }),
  tarjetasCredito: numeric('tarjetas_credito', { precision: 15, scale: 2 }),
  descuentoNomina: numeric('descuento_nomina', { precision: 15, scale: 2 }),
  pagoPrestamos: numeric('pago_prestamos', { precision: 15, scale: 2 }),
  otrosEgresos: numeric('otros_egresos', { precision: 15, scale: 2 }),
  detalleOtrosEgresos: text('detalle_otros_egresos'),
  totalEgresos: numeric('total_egresos', { precision: 15, scale: 2 }),
  inmuebles: jsonb('inmuebles').$type<Array<{ tipo: string; direccion: string; valorComercial: number }>>(),
  vehiculosActuales: jsonb('vehiculos_actuales').$type<Array<{ marca: string; linea: string; modelo: number; placa: string; prendaFavor?: string }>>(),
  referencias: jsonb('referencias').$type<Array<{ tipo: 'personal' | 'familiar' | 'comercial'; nombre: string; parentesco?: string; ciudad: string; telefono: string; nit?: string }>>(),
  declaraRenta: boolean('declara_renta'),
  patrimonioExterior: boolean('patrimonio_exterior'),
  operacionesMonedaExtranjera: boolean('operaciones_moneda_extranjera'),
  manejaRecursosPublicos: boolean('maneja_recursos_publicos'),
  esPEP: boolean('es_pep'),
  familiarPEP: boolean('familiar_pep'),
  origenFondos: jsonb('origen_fondos').$type<string[]>(),
  autorizaTratamientoDatos: boolean('autoriza_tratamiento_datos'),
  autorizaCentralesRiesgo: boolean('autoriza_centrales_riesgo'),
  autorizaContactoComercial: boolean('autoriza_contacto_comercial'),
  autorizaVerificacionSARLAFT: boolean('autoriza_verificacion_sarlaft'),
  autorizaConsultaPILA: boolean('autoriza_consulta_pila'),
  autorizaEliminacionDocumentos: boolean('autoriza_eliminacion_documentos'),
  declaraOrigenLicito: boolean('declara_origen_licito'),
  aceptaTerminos: boolean('acepta_terminos'),
  scoreInterno: integer('score_interno'),
  perfilRiesgo: text('perfil_riesgo'),
  capacidadPago: numeric('capacidad_pago', { precision: 15, scale: 2 }),
  multiploIngreso: numeric('multiplo_ingreso', { precision: 5, scale: 2 }),
  origenCliente: origenClienteEnum('origen_cliente'),
  ipSolicitud: text('ip_solicitud'),
  userAgent: text('user_agent'),
  firmaDigital: text('firma_digital'),
  creadoEn: timestamp('creado_en').defaultNow().notNull(),
  actualizadoEn: timestamp('actualizado_en').defaultNow().notNull(),
  enviadoEn: timestamp('enviado_en'),
  aprobadoEn: timestamp('aprobado_en'),
  desembolsadoEn: timestamp('desembolsado_en'),
  expiradoEn: timestamp('expirado_en'),
});
